/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fightScene.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import fightScene from './fightScene.glb'

export function FightScene(props) {
  const { nodes, materials } = useGLTF(fightScene)
  return (
    <group {...props} position={[0, 0, 0]} dispose={null}>
      <mesh geometry={nodes.Gravel_Garbage_Heap.geometry} material={materials.PX_Gravel_Garbage_Heap_01_LOD0} />
    </group>
  )
}

useGLTF.preload('/fightScene.glb')
