/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pathway.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import pathway from './pathway.glb'

export function PathWay(props) {
  const { nodes, materials } = useGLTF(pathway)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pathway_in_neighborhood_Photoscan.geometry} material={materials.neighborhood_aug3123_2_u1_v1} />
    </group>
  )
}

useGLTF.preload('/pathway.glb')
